#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export PYTHONPATH=integrated_data_processing
export SIMPLE_SETTINGS=settings

${PREFIX}pytest ${1-"./tests"} ${2}
#${PREFIX}black integrated_data_processing tests/ --check --diff
#${PREFIX}flake8 integrated_data_processing tests/
